version: '3.7'
services:
# Organizr front end combines all apps into one website
  organizr:
    container_name: $STACK-organizr
    image: organizrtools/organizr-v2
    restart: always
    labels:
      - "traefik.enable=true" # Enable reverse-proxy for this service
      - "traefik.frontend.rule=Host:$ORGANIZR.$DOMAIN" # Domain name for the app
      - "traefik.port=80"
    ports:
      - "80:80"
    environment:
      - PGID=$GROUPID
      - PUID=$USERID
    volumes:
      - organizr_config:/config
    networks:
      - ext_net

# Streaming & Compainion apps
  emby:
    container_name: $STACK-emby
    image: emby/embyserver
    restart: always
    labels:
      - "traefik.enable=true" # Enable reverse-proxy for this service
      - "traefik.frontend.rule=Host:$EMBY.$DOMAIN" # Domain name for the app
      - "traefik.frontend.auth.forward.address=http://organizr/api/?v1/auth&group=999"
      - "traefik.port=8096"
    ports:
      - "8096:8096"
      - "8097:8097"
    environment:
      - PGID=$GROUPID
      - PUID=$USERID
      - GIDLIST=$GROUPID
    volumes:
      - emby_config:/config
      - $MEDIA:/data/media
    networks:
      - ext_net

  # embystat:
  #   container_name: $STACK-emby_stat
  #   image: uping/embystat:nightly-ubuntu-x64
  #   restart: always
  #   depends_on:
  #     - emby
  #   labels:
  #     - "traefik.enable=true" # Enable reverse-proxy for this service
  #     - "traefik.frontend.rule=Host:$EMBYSTAT.$DOMAIN" # Domain name for the app
  #     - "traefik.frontend.auth.forward.address=http://organizr/api/?v1/auth&group=999"
  #     - "traefik.port=6555"
  #   networks:
  #     - ext_net

  jellyfin:
    container_name: $STACK-jellyfin
    image: linuxserver/jellyfin
    restart: always
    devices:
      - "/dev/dri:/dev/dri" # This is specific to my setup as my cpu supports intel quick sync
    labels:
      - "traefik.enable=true" # Enable reverse-proxy for this service
      - "traefik.frontend.rule=Host:$JELLYFIN.$DOMAIN" # Domain name for the app
      - "traefik.frontend.auth.forward.address=http://organizr/api/?v1/auth&group=999"
      - "traefik.port=8096"
    environment:
      - TZ=$TIMEZONE
      - PGID=$GROUPID
      - PUID=$USERID
    volumes:
      - jellyfin_config:/config
      - $MEDIA:/data/media
    networks:
      - ext_net

  plex:
    container_name: $STACK-$PLEX
    image: plexinc/pms-docker
    restart: always
    hostname: "$PLEXHOSTNAME"
    labels:
      - "traefik.enable=true" # Enable reverse-proxy for this service
      - "traefik.frontend.rule=Host:$PLEX.$DOMAIN" # Domain name for the app
      - "traefik.frontend.auth.forward.address=http://organizr/api/?v1/auth&group=999"
      - "traefik.port=32400"
    ports:
      - "32400:32400/tcp"
      - "3005:3005/tcp"
      - "8324:8324/tcp"
      - "32469:32469/tcp"
      - "1900:1900/udp"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
    environment:
      - ADVERTISE_IP="$ADVERTISEIP"
      - PLEX_CLAIM="$PLEXCLAIM"
      - PLEX_GID=$GROUPID
      - PLEX_UID=$USERID
      - TZ=$TIMEZONE
    volumes:
      - plex_config:/config
      - $TRANSCODE:/transcode
      - $MEDIA:/data/media
    networks:
      - ext_net

  airsonic:
    container_name: $STACK-airsonic
    image: linuxserver/airsonic
    restart: always
    depends_on:
      - organizr
    labels:
      - "traefik.enable=true" # Enable reverse-proxy for this service
      - "traefik.frontend.rule=Host:$AIRSONIC.$DOMAIN" # Domain name for the app
      - "traefik.frontend.auth.forward.address=http://organizr/api/?v1/auth&group=999"
      - "traefik.port=4040"
    environment:
      - TZ=$TIMEZONE
      - PGID=$GROUPID
      - PUID=$USERID
    volumes:
      - airsonic_config:/config
      - $MEDIA/music:/data/music
      - $MEDIA/playlists:/data/playlists
      - $MEDIA/podcasts:/data/podcasts
    networks:
      - ext_net

  ombi:
    container_name: $STACK-ombi
    image: linuxserver/ombi
    restart: always
    depends_on:
      - organizr
    labels:
      - "traefik.enable=true" # Enable reverse-proxy for this service
      - "traefik.frontend.rule=Host:$OMBI.$DOMAIN" # Domain name for the app
      - "traefik.frontend.auth.forward.address=http://organizr/api/?v1/auth&group=999"
      - "traefik.port=3579"
    environment:
      - TZ=$TIMEZONE
      - PGID=$GROUPID
      - PUID=$USERID
    volumes:
      - ombi_config:/config
    networks:
      - ext_net

  omv:
    image: qoomon/docker-host
    container_name: $STACK-omv
    restart: always
    cap_add: [ 'NET_ADMIN', 'NET_RAW' ]
    depends_on:
      - organizr
    labels:
      - "traefik.enable=true" # Enable reverse-proxy for this service
      - "traefik.frontend.rule=Host:$HOSTAPP.$DOMAIN" # Domain name for the app
      - "traefik.frontend.auth.forward.address=http://organizr/api/?v1/auth&group=1"
      - "traefik.port=$HOSTPORT"
    expose:
      - "$HOSTPORT"
    networks:
      - ext_net

# Indexer apps
  sonarr:
    container_name: $STACK-sonarr
    image: linuxserver/sonarr:preview
    restart: always
    depends_on:
      - organizr
    labels:
      - "traefik.enable=true" # Enable reverse-proxy for this service
      - "traefik.frontend.rule=Host:$SONARR.$DOMAIN" # Domain name for the app
      - "traefik.frontend.auth.forward.address=http://organizr/api/?v1/auth&group=1"
      - "traefik.port=8989"
    ports:
      - "8989:8989"
    environment:
      - TZ=$TIMEZONE
      - PGID=$GROUPID
      - PUID=$USERID
    volumes:
      - sonarr_config:/config
      - $MEDIA/temp:/data/temp
      - $MEDIA/tvshows:/data/tv
      - $MEDIA/kids_tvshows:/data/kids_tv
      - $MEDIA/anime_tv:/data/anime_tv
      - $DOWNLOADS/torrent:/data/downloads/torrent
      - $DOWNLOADS/usenet:/data/downloads/usenet
    networks:
      - ext_net

  radarr:
    container_name: $STACK-radarr
    image: linuxserver/radarr:nightly
    restart: always
    depends_on:
      - organizr
    labels:
      - "traefik.enable=true" # Enable reverse-proxy for this service
      - "traefik.frontend.rule=Host:$RADARR.$DOMAIN" # Domain name for the app
      - "traefik.frontend.auth.forward.address=http://organizr/api/?v1/auth&group=1"
      - "traefik.port=7878"
    ports:
      - "7878:7878"
    environment:
      - TZ=$TIMEZONE
      - PGID=$GROUPID
      - PUID=$USERID
    volumes:
      - radarr_config:/config
      - $MEDIA/temp:/data/temp
      - $MEDIA/movies:/data/movies
      - $MEDIA/kids_movies:/data/kids_movies
      - $MEDIA/anime_movies:/data/anime_movies
      - $DOWNLOADS/torrent:/data/downloads/torrent
      - $DOWNLOADS/usenet:/data/downloads/usenet
    networks:
      - ext_net

  radarr-collection:
    container_name: $STACK-radarr_collection
    image: si0972/radarr-collections
    restart: always
    depends_on:
      - radarr
    environment:
      - PGID=$GROUPID
      - PUID=$USERID
      - args=$ARGS
    volumes:
      - radarrcollection_config:/config
    networks:
      - ext_net

  lidarr:
    container_name: $STACK-lidarr
    image: linuxserver/lidarr
    restart: always
    depends_on:
      - organizr
    labels:
      - "traefik.enable=true" # Enable reverse-proxy for this service
      - "traefik.frontend.rule=Host:$LIDARR.$DOMAIN" # Domain name for the app
      - "traefik.frontend.auth.forward.address=http://organizr/api/?v1/auth&group=1"
      - "traefik.port=8686"
    ports:
      - "8686:8686"
    environment:
      - TZ=$TIMEZONE
      - PGID=$GROUPID
      - PUID=$USERID
    volumes:
      - lidarr_config:/config
      - $MEDIA/temp:/data/temp
      - $DOWNLOADS/torrent:/data/downloads/torrent
      - $DOWNLOADS/usenet:/data/downloads/usenet
      - $MEDIA/music:/data/music
    networks:
      - ext_net

# Indexer source apps
  jackett:
    container_name: $STACK-jackett
    image: linuxserver/jackett:development
    restart: always
    depends_on:
      - organizr
    labels:
      - "traefik.enable=true" # Enable reverse-proxy for this service
      - "traefik.frontend.rule=Host:$JACKETT.$DOMAIN" # Domain name for the app
      - "traefik.frontend.auth.forward.address=http://organizr/api/?v1/auth&group=1"
      - "traefik.port=9117"
    ports:
      - "9117:9117"
    environment:
      - TZ=$TIMEZONE
      - PGID=$GROUPID
      - PUID=$USERID
    volumes:
      - jackett_config:/config
      - $DOWNLOADS/torrent:/data/downloads/torrent
      - $DOWNLOADS/usenet:/data/downloads/usenet
    networks:
      - ext_net

# Torrent download clients
  transmission:
    container_name: $STACK-transmission
    image: haugene/transmission-openvpn
    restart: always
    cap_add:
      - NET_ADMIN
    dns:
      - 8.8.8.8
      - 8.8.4.4
    depends_on:
      - organizr
    labels:
      - "traefik.enable=true" # Enable reverse-proxy for this service
      - "traefik.frontend.rule=Host:$TRANSMISSION.$DOMAIN" # Domain name for the app
      - "traefik.frontend.auth.forward.address=http://organizr/api/?v1/auth&group=1"
      - "traefik.port=9091"
    ports:
      - 9091:9091
    environment:
      - PGID=$GROUPID
      - PUID=$USERID
      - CREATE_TUN_DEVICE=$CREATE_TUN_DEVICE
      - OPENVPN_PROVIDER=$OPENVPN_PROVIDER
      - OPENVPN_CONFIG=$OPENVPN_CONFIG
      - OPENVPN_USERNAME=$OPENVPN_USERNAME
      - OPENVPN_PASSWORD=$OPENVPN_PASSWORD
      - OPENVPN_OPTS=$OPENVPN_OPTS
      - NORDVPN_PROTOCOL=$NORDVPN_PROTOCOL
      - NORDVPN_CATEGORY=$NORDVPN_CATEGORY
      - WEBPROXY_ENABLED=false
      - LOCAL_NETWORK=$LOCAL_NETWORK
      - TRANSMISSION_DOWNLOAD_DIR=$TRANSMISSION_DOWNLOAD_DIR
      - TRANSMISSION_SCRAPE_PAUSED_TORRENTS_ENABLED=false
      - TRANSMISSION_RATIO_LIMIT_ENABLED=$TRANSMISSION_RATIO_LIMIT_ENABLED
      - TRANSMISSION_RATIO_LIMIT=$TRANSMISSION_RATIO_LIMIT
      - TRANSMISSION_IDLE_SEEDING_LIMIT_ENABLED=$TRANSMISSION_IDLE_SEEDING_LIMIT_ENABLED
      - TRANSMISSION_IDLE_SEEDING_LIMIT=$TRANSMISSION_IDLE_SEEDING_LIMIT
      - TRANSMISSION_DOWNLOAD_QUEUE_ENABLED=$TRANSMISSION_DOWNLOAD_QUEUE_ENABLED
      - TRANSMISSION_DOWNLOAD_QUEUE_SIZE=$TRANSMISSION_DOWNLOAD_QUEUE_SIZE
      - TRANSMISSION_PORT_FORWARDING_ENABLED=$TRANSMISSION_PORT_FORWARDING_ENABLED
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - $DOWNLOADS/torrent:/data/downloads/torrent
    networks:
      - ext_net

# Usenet download clients
  nzbget:
    image: "linuxserver/nzbget:testing"
    container_name: $STACK-nzbget
    restart: always
    depends_on:
      - organizr
    labels:
      - "traefik.enable=true" # Enable reverse-proxy for this service
      - "traefik.frontend.rule=Host:$NZBGET.$DOMAIN" # Domain name for the app
      - "traefik.frontend.auth.forward.address=http://organizr/api/?v1/auth&group=1"
      - "traefik.port=6789"
    ports:
      - 6789:6789
    environment:
      - PUID=$USERID
      - PGID=$GROUPID
      - TZ=$TIMEZONE
    volumes:
      - nzbget_config:/config
      - $DOWNLOADS/usenet:/data/downloads/usenet
    networks:
      - ext_net

# Utility services
  ddclient:
    image: "linuxserver/ddclient"
    container_name: $STACK-ddclient
    restart: always
    environment:
      - PUID=$USERID
      - PGID=$GROUPID
      - TZ=$TIMEZONE
    volumes:
      - ddclient_config:/config
    networks:
      - ext_net

  portainer:
    image: "portainer/portainer"
    container_name: $STACK-portainer
    restart: always
    depends_on:
      - organizr
    labels:
      - "traefik.enable=true" # Enable reverse-proxy for this service
      - "traefik.frontend.rule=Host:$PORTAINER.$DOMAIN" # Domain name for the app
      - "traefik.frontend.auth.forward.address=http://organizr/api/?v1/auth&group=1"
      - "traefik.port=9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_config:/data
    networks:
      - ext_net

  nextcloud:
    image: "nextcloud"
    container_name: $STACK-nextcloud
    restart: always
    labels:
      - "traefik.enable=true" # Enable reverse-proxy for this service
      - "traefik.frontend.rule=Host:$NEXTCLOUD.$DOMAIN" # Domain name for the app
      - "traefik.frontend.auth.forward.address=http://organizr/api/?v1/auth&group=999"
      - "traefik.port=80"
    volumes:
      - nextcloud_config:/var/www/html
    networks:
      - ext_net

  nextcloud:
    image: "nextcloud"
    container_name: $STACK-nextcloud
    restart: always
    labels:
      - "traefik.enable=true" # Enable reverse-proxy for this service
      - "traefik.frontend.rule=Host:$NEXTCLOUD.$DOMAIN" # Domain name for the app
      - "traefik.frontend.auth.forward.address=http://organizr/api/?v1/auth&group=999"
      - "traefik.port=80"
    volumes:
      - nextcloud_config:/var/www/html
      - $NEXTCLOUD_DATA:/var/www/html/data
      - $NEXTCLOUD_LOCALDIR:/data/local
    networks:
      - ext_net

  # duplicati:
  #   image: "linuxserver/duplicati"
  #   container_name: $STACK-duplicati
  #   restart: always
  #   depends_on:
  #     - organizr
  #   labels:
  #     - "traefik.enable=true" # Enable reverse-proxy for this service
  #     - "traefik.frontend.rule=Host:$DUPLICATI.$DOMAIN" # Domain name for the app
  #     - "traefik.frontend.auth.forward.address=http://organizr/api/?v1/auth&group=1"
  #     - "traefik.port=8200"
  #   environment:
  #     - PUID=$USERID
  #     - PGID=$GROUPID
  #     - TZ=$TIMEZONE
  #   volumes:
  #     - duplicati_config:/config
  #   networks:
  #     - ext_net

  pihole:
    image: "pihole/pihole:latest"
    container_name: $STACK-pihole
    restart: always
    depends_on:
      - organizr
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    # cap_add:
    #   - NET_ADMIN
    dns:
      - 127.0.0.1
      - 1.1.1.1
    labels:
      - "traefik.enable=true" # Enable reverse-proxy for this service
      - "traefik.frontend.rule=Host:$PIHOLE.$DOMAIN" # Domain name for the app
      - "traefik.port=80"
    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.backend=pihole"
    #   - "traefik.port=80"
    #   - "traefik.frontend.rule=Host:$PIHOLE.$DOMAIN" # Domain name for the app
    #   - "traefik.frontend.rule=HostRegexp:$PIHOLE.$DOMAIN,{catchall:.*}"
    #   - "traefik.frontend.priority=1"
    #   - traefik.frontend.headers.SSLRedirect=true
    #   - traefik.frontend.headers.STSSeconds=315360000
    #   - traefik.frontend.headers.browserXSSFilter=true
    #   - traefik.frontend.headers.contentTypeNosniff=true
    #   - traefik.frontend.headers.forceSTSHeader=true
    #   - traefik.frontend.headers.SSLHost=$DOMAIN
    #   - traefik.frontend.headers.STSIncludeSubdomains=true
    #   - traefik.frontend.headers.STSPreload=true
    #   - traefik.frontend.headers.frameDeny=true
    #   - traefik.frontend.auth.forward.address=http://organizr/api/?v1/auth&group=1
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8183:80"
      - "8184:443"
    environment:
      - TZ=$TIMEZONE
      # WEBPASSWORD: 'set a secure password here or it will be random'
    volumes:
       - pihole_config:/etc/pihole/
       - pihole_dnsmasq.d:/etc/dnsmasq.d/
      #  - ./config/pihole/allow-iframe.sh:/etc/cont-init.d/21-allow-iframe.sh
    networks:
      - ext_net

volumes:
  organizr_config:
  emby_config:
  jellyfin_config:
  plex_config:
  airsonic_config:
  ombi_config:
  sonarr_config:
  radarr_config:
  radarrcollection_config:
  lidarr_config:
  jackett_config:
  nzbget_config:
  ddclient_config:
  portainer_config:
  nextcloud_config:
  # duplicati_config:
  pihole_config:
  pihole_dnsmasq.d:

networks:
  ext_net:
    name: mediacenter_ext_net
