version: '3.4'
services:
# Organizr front end combines all apps into one website
  organizr:
    container_name: $STACK-$ORGANIZR
    image: organizrtools/organizr-v2
    restart: always
    ports:
      - "8888:80"
    environment:
      - VIRTUAL_HOST=$ORGANIZR.$DOMAIN
      - PGID=$GROUPID
      - PUID=$USERID
    volumes:
      - $APPDATA/$STACK/$ORGANIZR:/config
    networks:
      - ext_net

# Streaming & Compainion apps
  emby:
    container_name: $STACK-$EMBY
    image: emby/embyserver
    restart: always
    depends_on:
      - organizr
    ports:
      -  "8096:8096"
    environment:
      - PGID=$GROUPID
      - PUID=$USERID
      - GIDLIST=$GROUPID
    volumes:
      - $APPDATA/$STACK/$EMBY:/config
      - $MEDIA:/data/media
    networks:
      - ext_net

  # embystat:
  #   container_name: $STACK-$EMBYSTAT
  #   image: uping/embystat:latest-linux
  #   restart: always
  #   depends_on:
  #     - emby
  #   networks:
  #     - ext_net

  # jellyfin:
  #   container_name: $STACK-$JELLYFIN
  #   image: linuxserver/jellyfin
  #   restart: always
  #    depends_on:
  #      - organizr
  #   ports:
  #     - 8097:8096
  #   environment:
  #     - TZ=$TIMEZONE
  #     - PGID=$GROUPID
  #     - PUID=$USERID
  #   volumes:
  #     - $APPDATA/$STACK/$JELLYFIN:/config
  #     - $MEDIA:/data/media
  #   networks:
  #     - ext_net

  airsonic:
    container_name: $STACK-$AIRSONIC
    image: linuxserver/airsonic
    restart: always
    depends_on:
      - organizr
    environment:
      - TZ=$TIMEZONE
      - PGID=$GROUPID
      - PUID=$USERID
    volumes:
      - $APPDATA/$STACK/$AIRSONIC:/config
      - $MEDIA/music:/data/music
      - $MEDIA/playlists:/data/playlists
      - $MEDIA/podcasts:/data/podcasts
    networks:
      - ext_net

  ombi:
    container_name: $STACK-$OMBI
    image: linuxserver/ombi
    restart: always
    depends_on:
      - organizr
    environment:
      - TZ=$TIMEZONE
      - PGID=$GROUPID
      - PUID=$USERID
    volumes:
      - $APPDATA/$STACK/$OMBI:/config
    networks:
      - ext_net

  omv:
    image: qoomon/docker-host
    container_name: $STACK-$HOSTAPP
    restart: always
    cap_add: [ 'NET_ADMIN', 'NET_RAW' ]
    depends_on:
      - organizr
    expose:
      - "$HOSTPORT"
    networks:
      - ext_net

# Indexer apps
  sonarr:
    container_name: $STACK-$SONARR
    image: linuxserver/sonarr:preview
    restart: always
    depends_on:
      - organizr
    ports:
      - "8989:8989"
    environment:
      - TZ=$TIMEZONE
      - PGID=$GROUPID
      - PUID=$USERID
    volumes:
      - $APPDATA/$STACK/$SONARR:/config
      - $MEDIA/temp:/data/temp
      - $MEDIA/tvshows:/data/tv
      - $DOWNLOADS/torrent:/data/downloads/torrent
      - $DOWNLOADS/usenet:/data/downloads/usenet
    networks:
      - ext_net

  radarr:
    container_name: $STACK-$RADARR
    image: linuxserver/radarr:nightly
    restart: always
    depends_on:
      - organizr
    ports:
      - "7878:7878"
    environment:
      - TZ=$TIMEZONE
      - PGID=$GROUPID
      - PUID=$USERID
    volumes:
      - $APPDATA/$STACK/$RADARR:/config
      - $MEDIA/temp:/data/temp
      - $MEDIA/movies:/data/movies
      - $DOWNLOADS/torrent:/data/downloads/torrent
      - $DOWNLOADS/usenet:/data/downloads/usenet
    networks:
      - ext_net

  radarr-collection:
    container_name: $STACK-$RADARRCOLLECTION
    image: si0972/radarr-collections
    restart: always
    depends_on:
      - radarr
    environment:
      - PGID=$GROUPID
      - PUID=$USERID
      - args=$ARGS
    volumes:
      - $APPDATA/$STACK/$RADARRCOLLECTION:/config
    networks:
      - ext_net

  lidarr:
    container_name: $STACK-$LIDARR
    image: linuxserver/lidarr
    restart: always
    depends_on:
      - organizr
    ports:
      - "8686:8686"
    environment:
      - TZ=$TIMEZONE
      - PGID=$GROUPID
      - PUID=$USERID
    volumes:
      - $APPDATA/$STACK/$LIDARR:/config
      - $MEDIA/temp:/data/temp
      - $DOWNLOADS/torrent:/data/downloads/torrent
      - $DOWNLOADS/usenet:/data/downloads/usenet
      - $MEDIA/music:/data/music
    networks:
      - ext_net

# Indexer source apps
  jackett:
    container_name: $STACK-$JACKETT
    image: linuxserver/jackett:development
    restart: always
    depends_on:
      - organizr
    ports:
      - "9117:9117"
    environment:
      - TZ=$TIMEZONE
      - PGID=$GROUPID
      - PUID=$USERID
    volumes:
      - $APPDATA/$STACK/$JACKETT:/config
      - $DOWNLOADS/torrent:/data/downloads/torrent
      - $DOWNLOADS/usenet:/data/downloads/usenet
    networks:
      - ext_net

# Torrent download clients
  transmission:
    container_name: $STACK-$TRANSMISSION
    image: haugene/transmission-openvpn
    restart: always
    cap_add:
      - NET_ADMIN
    dns:
      - 8.8.8.8
      - 8.8.4.4
    depends_on:
      - organizr
    ports:
      - 9091:9091
    environment:
      - PGID=$GROUPID
      - PUID=$USERID
      - CREATE_TUN_DEVICE=$CREATE_TUN_DEVICE
      - OPENVPN_PROVIDER=$OPENVPN_PROVIDER
      - OPENVPN_CONFIG=$OPENVPN_CONFIG
      - OPENVPN_USERNAME=$OPENVPN_USERNAME
      - OPENVPN_PASSWORD=$OPENVPN_PASSWORD
      - OPENVPN_OPTS=$OPENVPN_OPTS
      - NORDVPN_PROTOCOL=$NORDVPN_PROTOCOL
      - NORDVPN_CATEGORY=$NORDVPN_CATEGORY
      - WEBPROXY_ENABLED=false
      - LOCAL_NETWORK=$LOCAL_NETWORK
      - TRANSMISSION_DOWNLOAD_DIR=$TRANSMISSION_DOWNLOAD_DIR
      - TRANSMISSION_SCRAPE_PAUSED_TORRENTS_ENABLED=false
      - TRANSMISSION_RATIO_LIMIT_ENABLED=$TRANSMISSION_RATIO_LIMIT_ENABLED
      - TRANSMISSION_RATIO_LIMIT=$TRANSMISSION_RATIO_LIMIT
      - TRANSMISSION_IDLE_SEEDING_LIMIT_ENABLED=$TRANSMISSION_IDLE_SEEDING_LIMIT_ENABLED
      - TRANSMISSION_IDLE_SEEDING_LIMIT=$TRANSMISSION_IDLE_SEEDING_LIMIT
      - TRANSMISSION_DOWNLOAD_QUEUE_ENABLED=$TRANSMISSION_DOWNLOAD_QUEUE_ENABLED
      - TRANSMISSION_DOWNLOAD_QUEUE_SIZE=$TRANSMISSION_DOWNLOAD_QUEUE_SIZE
      - TRANSMISSION_PORT_FORWARDING_ENABLED=$TRANSMISSION_PORT_FORWARDING_ENABLED
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - $DOWNLOADS/torrent:/data/downloads/torrent
    networks:
      - ext_net

# Usenet download clients
  nzbget:
    image: "linuxserver/nzbget:testing"
    container_name: $STACK-$NZBGET
    restart: always
    depends_on:
      - organizr
    ports:
      - 6789:6789
    environment:
      - PUID=$USERID
      - PGID=$GROUPID
      - TZ=$TIMEZONE
    volumes:
      - $APPDATA/$STACK/$NZBGET:/config
      - $DOWNLOADS/usenet:/data/downloads/usenet
    networks:
      - ext_net

# Utility services
  ddclient:
    image: "linuxserver/ddclient"
    container_name: $STACK-ddclient
    restart: always
    environment:
      - PUID=$USERID
      - PGID=$GROUPID
      - TZ=$TIMEZONE
    volumes:
      - $APPDATA/$STACK/ddclient:/config
    networks:
      - ext_net

  portainer:
    image: "portainer/portainer"
    container_name: $STACK-$PORTAINER
    restart: always
    depends_on:
      - organizr
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $APPDATA/$STACK/$PORTAINER:/data
    networks:
      - ext_net

networks:
  ext_net:
    external:
      name: $EXT_NET
